---
- name: Collect facts
  become: true
  ansible.builtin.setup:
    filter:
      - distribution

- name: Install git on Debian
  ansible.builtin.include_tasks:
    file: Debian.yml
  when:
    - ansible_facts.distribution == "Debian"

- name: Install git on Ubuntu
  ansible.builtin.include_tasks:
    file: Ubuntu.yml
  when:
    - ansible_facts.distribution == "Ubuntu"

- name: Setup system git config
  become: true
  community.general.ini_file:
    path: "{{ git_config_system_path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: '0644'
    state: present
  loop: "{{ git_config_system_values }}"
  when: git_config_system_values | length >= 1

- name: Setup global git config
  community.general.ini_file:
    path: "{{ git_config_global_path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: '0644'
    state: present
  loop: "{{ git_config_global_values }}"
  when: git_config_global_values | length >= 1

- name: Copy git template directory
  ansible.builtin.copy:
    src: "{{ git_template_src_dir }}"
    dest: "{{ git_template_dest_dir }}"
  when:
    - git_template_src_dir | length >= 1
    - git_template_dest_dir | length >= 1
