---
- name: Collect facts
  become: true
  ansible.builtin.setup:

- name: Install git on Debian
  ansible.builtin.include_tasks:
    file: Debian.yml
  when:
    - ansible_facts.distribution == "Debian"

- name: Install git on Ubuntu
  ansible.builtin.include_tasks:
    file: Ubuntu.yml
  when:
    - ansible_facts.distribution == "Ubuntu"
