---
dependency:
  name: galaxy
  options:
    requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: ubuntu_focal
    image: ubuntu:focal
  - name: ubuntu_jammy
    image: ubuntu:jammy
  - name: debian_bullseye
    image: debian:bullseye
  - name: debian_bookworm
    image: debian:bookworm
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        git_config_system_values:
          - section: core
            option: filemode
            value: "false"
        git_config_global_values:
          - section: core
            option: gitProxy
            value: ssh
verifier:
  name: ansible

