---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_focal
    image: ubuntu:focal
  - name: ubuntu_jammy
    image: ubuntu:jammy
  - name: debian_bullseye
    image: debian:bullseye
  - name: debian_bookworm
    image: debian:bookworm
provisioner:
  name: ansible
  playbooks:
    prepare: ../playbooks/prepare.yml
verifier:
  name: ansible
