---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather the package facts
      become: true
      ansible.builtin.package_facts:
        manager: auto

    - name: Check that git package installed
      ansible.builtin.assert:
        that:
          - "'git' in ansible_facts.packages"

    - ansible.builtin.command: git config --system -l
      register: get_git_config_system
    - debug: var=get_git_config_system

    - ansible.builtin.command: git config --global -l
      register: get_git_config_global
    - debug: var=get_git_config_global
